### ISSUE TITLE
Starting local dev server goes on endless loop throwing string comparison error

### ISSUE THREAD

**Issue by dsp1589** [discourse/mini_scheduler#11]
Am new to Discourse! if this issue is ignorable please comment! 

I tried starting discourse dev server in my local Mac machine and facing this endless loop of logs with repeated error message stating that "comparison of String with 1618852392 failed"

`mini_scheduler/lib/mini_scheduler/schedule_info.rb`

Looks like we are comparing Int with String in line number 38 in above .rb file. Am not sure this is causing this issue. But am able to access discourse server using http://localhost:3000/ in browser. (logs are just repeating and am afraid it could cause performance issue). Attached logs from my terminal after starting the dev server using `bundle exec rails server`

Attached a Video URL to understand what's happening: https://www.youtube.com/watch?app=desktop&v=Pbj4tplJso0 

[endless loop.txt](https://github.com/discourse/mini_scheduler/files/6340741/endless.loop.txt)

**Comment by SamSaffron** [comment]
It is very hard to debug this without a repro. Looks related to Discourse, if you are able to repro from a clean install can you report this on meta.discourse.org?  

Simplest workaround is `redis-cli flushall` which will reset everything.

**Comment by dsp1589** [comment]
mini_scheduler should have a sanity check before comparing the data retrieved?

Yeah, already did the workaround and it's fine now. I thought this was due to some missing sanity check on the data retrieved from redis cache and I Just wanted to report the issue.
