### ISSUE TITLE
Is this the correct way to configure mini_schedule and workers?

### ISSUE THREAD

**Issue by diegolinhares** [discourse/mini_scheduler#12]
I was testing this gem and found a problem that my scheduled worker wasn't recognized.

I had to [require](https://github.com/diegolinhares/mini_scheduler_test/blob/f3033fa58aefbb3dea43b7db31896efb77d2a406/config/initializers/mini_scheduler.rb#L3) my workers before the MiniScheduler configuration the same way I saw in discourse to fix my **mini_scheduler** initializer. After, I got an error describing that my worker didn't have the **perform** method. I [added](https://github.com/diegolinhares/mini_scheduler_test/blob/f3033fa58aefbb3dea43b7db31896efb77d2a406/app/workers/base_worker.rb#L7) the perform method and called the **execute** method and I got it all working.

Is this the correct way to use this gem? Am I missing something?

One more thing this was in the README:
 "To view the scheduled jobs, their history, and the schedule, go to sidekiq's web UI and look for the "Scheduler" tab at the top." 

I had to add the **require 'mini_scheduler/web'** to my config/routes.rb to got this working as well.

I think it will be good to add these points to the README.

Thanks  :)

**Comment by SamSaffron** [comment]
I agree entirely we should improve the README, PR welcome. 

Usage is: 

```
class Something
   extend MiniScheduler::Schedule
   
   every 1.hour

   def perform
      # do work
   end
end
```
