### ISSUE TITLE
Scheduler not enqueuing jobs

### ISSUE THREAD

**Issue by Papipo** [discourse/mini_scheduler#3]
Hi!

I made sure that both sidekiq and MiniScheduler use the same redis URL. I also made sure that Scheduled jobs are loaded before calling `MiniScheduler.start`, so it's able to discover them.

But I don't see anything on the logs nor the sidekiq UI.

Thanks!

**Comment by Papipo** [comment]
I've been diggin' further and it seems that the jobs end up running, but due to some random feature of `mini_scheduler` they can run 3, 4 minutes later than expected.

This gem documentation needs some love! <3

Anyway, thanks for the gem, it's the one I like the most for scheduling with sidekiq by far.

**Comment by SamSaffron** [comment]
Totally agree about getting the documentation into a good state, do you care to give a shot at improving stuff? The jitter is there to ensure schedulers that are deployed to a big cluster don't cause a giant spike regularly at a consistent time.

**Comment by Papipo** [comment]
Sure, I'll take a stab at it if I find some spare time.

But for example this very feature, I'm not entirely sure how it is supposed to work. I mean, how much extra time can it add to a given task? I'd guess it's based on the actual `every` value of the task. But I have a task that runs `every 1.minute` and when restarting my worker it takes like 3 or 4 minutes to run again, and that seems to be too much.
