### ISSUE TITLE
Error handler causes more errors

### ISSUE THREAD

**Issue by dmke** [discourse/mini_scheduler#8]
This line:

https://github.com/discourse/mini_scheduler/blob/4f2994147bbb6dace98e967ed2673cd364588dfa/lib/mini_scheduler/manager.rb#L95

causes problems with the Sidekiq integration for `sentry-raven`:

```ruby
# https://github.com/getsentry/sentry-ruby/blob/3.1.1/lib/raven/integrations/sidekiq/error_handler.rb#L24-L27
def transaction_from_context(context)
  classname = (context["wrapped"] || context["class"] ||
    (context[:job] && (context[:job]["wrapped"] || context[:job]["class"]))
  )
  ...
end
```

I've had setup a scheduled worker to cleanup my database, which didn't do its job properly for over a month. Today I've noticed this in the server logs:

```log
2020-11-25T23:00:02.261Z pid=35798 tid=3ra WARN: {"message":"Running a scheduled job","job":"CleanupWorker"}
2020-11-25T23:00:02.261Z pid=35798 tid=3ra WARN: ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "doesntmatter" violates foreign key constraint "fk_rails_whatever" on table "doesntmatter"
DETAIL:  Key (id)=(42 is still referenced from table "doesntmatter".
(Rails stack trace omitted)
2020-11-25T23:00:02.261Z pid=35798 tid=3ra ERROR: !!! ERROR HANDLER THREW AN ERROR !!!
2020-11-25T23:00:02.261Z pid=35798 tid=3ra ERROR: undefined method `[]' for CleanupWorker:Class
2020-11-25T23:00:02.262Z pid=35798 tid=3ra ERROR: $HOME/shared/bundle/ruby/2.7.0/gems/sentry-raven-3.1.1/lib/raven/integrations/sidekiq/error_handler.rb:26:in `transaction_from_context'
$HOME/shared/bundle/ruby/2.7.0/gems/sentry-raven-3.1.1/lib/raven/integrations/sidekiq/error_handler.rb:10:in `call'
$HOME/shared/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/exception_handler.rb:19:in `block in handle_exception'
$HOME/shared/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/exception_handler.rb:18:in `each'
$HOME/shared/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/exception_handler.rb:18:in `handle_exception'
```

I'm tempted to inject a custom exception handler, like this:

```ruby
MiniScheduler.configure do |config|
  config.job_exception_handler do |ex, ctx|
    ctx["class"] = ctx.delete(:job) if ctx[:job].is_a?(Class)
    Sidekiq::ExceptionHandler.handle_exception(ex, ctx)
  end
end
```

But of course, I'd like to see this fixed here :-)

I don't know the internals of Sidekiq that much, maybe the job hash was changed some time in the past? Not sure what the correct solution is.

**Comment by SamSaffron** [comment]
As in this line: 

https://github.com/discourse/mini_scheduler/blob/4f2994147bbb6dace98e967ed2673cd364588dfa/lib/mini_scheduler.rb#L28

I am open to fix this if the signature on sidekiq error handlers has changed, will require digging into sidekiq internals.

**Comment by dmke** [comment]
I did some digging:

It looks like this commit introduced `:job`: https://github.com/mperham/sidekiq/commit/8c53356fc8e6ff24ba739fed70a81d3c0ad0d907

> This commit ensures that exception handlers are always provided with two objects:
> 
> * The Exception
> * A hash with the following keys:
>   * `:context` (Required) - A String message explaining what happened
>   * `:job` (Optional) - If this occurred while a job was being processed, this is the deserialized job Hash
>   * `:jobstr` (Optional) - If this occurred during job deserialization, this is the raw JSON string of the job
>   * `:event` (Optional) - If this occurred during a lifecycle event, name of the event

Before that, Sidekiq called `handle_exception(ex, job_hash || { job: a_string })`. (`context["class"]` has just moved to `context[:job]["class"]`).

The earliest Sidekiq version supporting this seems to be v4.2.3 (Oct. 2016). It was authored for [this PR in sentry-raven](https://github.com/getsentry/sentry-ruby/pull/555).

I assume it is safe to call `handle_exception` like so:

```ruby
# spec.add_dependency "sidekiq", ">= 4.2.3"
MiniScheduler.handle_job_exception(e, message: "Running a scheduled job", job: { "class" => klass })
```

or, if you don't want to raise the minimal Sidekiq version:

```ruby
module MiniScheduler
  SIDEKIQ_LEGACY_EXCEPTION_PROTOCOL = Gem::Version.new(Sidekiq::VERSION) < Gem::Version.new("4.2.3")

  def self.handle_job_exception(ex, context = {})
    context[:job] = { "class" => context[:job] } if SIDEKIQ_LEGACY_EXCEPTION_PROTOCOL

    if job_exception_handler
      job_exception_handler.call(ex, context)
    else
      SidekiqExceptionHandler.handle_exception(ex, context)
    end
  end
end
```

**Comment by SamSaffron** [comment]
I support raising the minimum version of sidekiq

Can you submit a PR for this ?

**Comment by dmke** [comment]
Sure, can do. It might take me a day until I find a moment to do so :-)

**Comment by dmke** [comment]
PR is ready for review.
